### ISSUE TITLE
error: use of undeclared identifier 'openpty'

### ISSUE THREAD

**Issue by ghost** [Gottox/node-webterm#4]
There is an error on Mac OS X 10.10.3:

> $ sudo npm install
> ....
> child_pty@0.3.1 install ~/www/node-webterm/node_modules/child_pty
> node-gyp rebuild
> 
>  CXX(target) Release/obj.target/exechelper/src/exechelper.o
>  LINK(target) Release/exechelper
>  LINK(target) Release/exechelper: Finished
>  CXX(target) Release/obj.target/pty/src/pty.o
> ../src/pty.cpp:51:5: error: use of undeclared identifier 'openpty'
>        if(openpty(&master, &slave, NULL, NULL, &w) < 0)
>           ^
> 1 error generated.
> make: **\* [Release/obj.target/pty/src/pty.o] Error 1
> .....

**Comment by Gottox** [comment]
Please retry master.

**Comment by ghost** [comment]
Retried once again, child_pty build complete successfully.
Thanks!
