### ISSUE TITLE
Can not show ANSI color code

### ISSUE THREAD

**Issue by lilijreey** [Gottox/node-webterm#7]
Hi, I test your app, I use Ubuntu 14.04.  My PS1 is  
 export PS1="${debian_chroot:+($debian_chroot)}(git-$gi_branch):\e[01;34m\w\e[00m\$ "
but can not show this. But I switch to Fish shell, everything is Ok. Why?
![screenshot from 2016-08-02 09 55 05](https://cloud.githubusercontent.com/assets/1732373/17314477/51bedb0a-5897-11e6-9739-88ca951b950e.png)

**Comment by Gottox** [comment]
Looks like escape codes do not work with `/bin/sh` on your system. replace `/bin/sh` with `/bin/bash` or `$SHELL` in `config.json`.
